#!/bin/sh

while read file
do
fullpath="$(pwd)/$file"
 case "$1" in
 "s")
	feh --bg-scale "$file"
	notify-send "Wallpaper changed." ;;
 "y")
	xclip -selection clipboard "$file"
	notify-send "copied to clipboard"  ;;
 "D")
     	rm "$file"
     	notify-send "File Deleted" & ;;
 "r")
	convert -rotate 90 "$file" "$file" ;;
 "R")
	convert -rotate -90 "$file" "$file" ;;
 "f")
	convert -flop "$file" "$file" ;;
 "G")
	gimp "$file" & ;;
 esac
done
