resolver: lts-17.5
packages:
- xmobar-git
- xmonad-git
- xmonad-contrib-git
extra-deps:
- netlink-1.1.1.0@sha256:d83424b5ba9921191449e4b1f53c7cba7f4375f2c55a9b737c77e982e1f40d00,3689
flags:
  xmobar:
    all_extensions: true
extra-package-dbs: []
