resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/20/13.yaml
packages:
- xmobar-git
- xmonad-git
- xmonad-contrib-git
flags:
  xmobar:
    all_extensions: true
extra-package-dbs: []
extra-deps:
  - netlink-1.1.1.0
