#! /bin/sh
~/.local/bin/bars/lemon_bar | lemonbar -gx22 -f "Monospace:pixelsize=14" -B "#D9000000" -F "#ffffc8"  &
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
picom -b &

bspc monitor -d 1 2 3 4 5 6 7 8 9 
bspc config border_width         1
bspc config window_gap           8
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#d8dee8" 
bspc config normal_border_color  "#2f343f"
bspc rule -a mpv state=floating

