#! /bin/sh
./.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &
picom -b &
bspc monitor -d I II III IV V #VI VII VIII IX X
bspc config border_width         1
bspc config window_gap          2

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mpv state=floating
