#! /bin/sh

~/.local/bin/lemonbar.sh | lemonbar -gx22 -f "FiraCode Nerd Font:style=Light:pixelsize=13" -B "#E6080808" -F "#ffffc8"  &
#$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom -b &
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5
bspc config border_width         1
bspc config window_gap          2
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a mpv state=floating
